name: Test Rollup Jobs

on:
  pull_request:
    branches: [main, master]

jobs:
  timeout-job:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Long running step (will timeout)
        run: |
          sleep 90

  timeout-job-incorrect-result:
    runs-on: ubuntu-latest
    needs: timeout-job
    if: ${{ failure() || cancelled() }}
    steps:
      - run: exit 1

  timeout-job-correct-result:
    runs-on: ubuntu-latest
    needs: timeout-job
    if: ${{ always() }}
    steps:
      - if: ${{ needs.timeout-job.result != 'success' }}
        run: exit 1

  failure-job:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  failure-job-result:
    runs-on: ubuntu-latest
    needs: failure-job
    if: ${{ failure() }}
    steps:
      - run: exit 1

  failure-job-robust-result:
    runs-on: ubuntu-latest
    needs: failure-job
    if: ${{ always() }}
    steps:
      - if: ${{ needs.failure-job.result != 'success' }}
        run: exit 1

  rollup-job-incorrect-result:
    runs-on: ubuntu-latest
    needs: [failure-job, timeout-job]
    if: ${{ failure() || cancelled() }}
    steps:
      - run: exit 1

  rollup-job-correct-result:
    runs-on: ubuntu-latest
    needs: [failure-job, timeout-job]
    if: ${{ always() }}
    steps:
      - if: ${{ needs.failure-job.result != 'success' || needs.timeout-job.result != 'success' }}
        run: exit 1
