on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      # set to "true" to run the rollup-all
      run_rollup_all: ${{steps.run_rollup_all.outputs.run_rollup_all}}
      # set to "true" to run a-shard
      run_a: ${{steps.run_rollup_all.outputs.run_a}}
      # set to "true" to run b-shard
      run_b: ${{steps.run_rollup_all.outputs.run_b}}
      # set fail_a_number to the shard number (if desired) that should fail
      fail_a_number: ${{steps.run_rollup_all.outputs.fail_a_number}}
      # set fail_b_number to the shard number (if desired) that should fail
      fail_b_number: ${{steps.run_rollup_all.outputs.fail_b_number}}
    steps:
      - id: run_rollup_all
        run: |
          echo "run_rollup_all=true" >> "$GITHUB_OUTPUT"
          echo "run_a=true" >> "$GITHUB_OUTPUT"
          echo "run_b=true" >> "$GITHUB_OUTPUT"
          echo "fail_a_number=" >> "$GITHUB_OUTPUT"
          echo "fail_b_number=" >> "$GITHUB_OUTPUT"
      - run: sleep 3

  # test-step-status:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo hi
  #     - if: success()
  #       run: echo "this runs because all prev steps in this job succeeded"
  #     - run: exit 1
  #     - if: failure()
  #       run: echo "this will run because some prev step failed"
  #     - if: always()
  #       run: echo "this runs too"
  #     - if: success()
  #       run: echo "this does not run bc a prev step failed"
  #     - run: echo "this does not run either bc a prev step failed"

  a-shard:
    runs-on: ubuntu-latest
    needs: [configure]
    if: ${{ needs.configure.outputs.run_a == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        number: [1, 2]
    steps:
      - run: |
          echo ${{ matrix.number }}
          if [[ "${{ matrix.number }}" == "${{ needs.configure.outputs.fail_a_number }}" ]]; then
            echo "failing shard ${{ matrix.number}}"
            exit 1
          else
              echo "passing shard ${{ matrix.number }}"
          fi

  roll-up-a:
    needs: [a-shard]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - run: echo "a-shard failed" && exit 1

  b-shard:
    needs: [configure]
    if: ${{ needs.configure.outputs.run_b == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        number: [1, 2]
    steps:
      - run: |
          echo ${{ matrix.number }}
          if [[ "${{ matrix.number }}" == "${{ needs.configure.outputs.fail_b_number }}" ]]; then
            echo "failing shard ${{ matrix.number}}"
            exit 1
          else
              echo "passing shard ${{ matrix.number }}"
          fi

  roll-up-b:
    needs: [b-shard]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - run: echo "b-shard failed" && exit 1

  roll-up-all:
    runs-on: ubuntu-latest
    needs: [roll-up-a, roll-up-b, configure]
    if: ${{ !cancelled() && needs.configure.outputs.run_rollup_all == 'true' }}
    steps:
      - run: echo rollup-a-result=${{ needs.roll-up-a.result }}
      - run: echo rollup-b-result=${{ needs.roll-up-b.result }}
      - if: ${{ needs.roll-up-a.result == 'failure' }}
        run: echo "a failed" && exit 1
      - if: ${{ needs.roll-up-b.result == 'failure' }}
        run: echo "b failed" && exit 1
