on:
  pull_request:
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      run_rollup_all: ${{steps.run_rollup_all.outputs.run_rollup_all}}
      run_a: ${{steps.run_rollup_all.outputs.run_a}}
      run_b: ${{steps.run_rollup_all.outputs.run_b}}
    steps:
      - id: run_rollup_all
        run: |
          echo "run_rollup_all=true" >> "$GITHUB_OUTPUT"
          echo "run_a=true" >> "$GITHUB_OUTPUT"
          echo "run_b=true" >> "$GITHUB_OUTPUT"
      - run: sleep 30

  a-shard:
    runs-on: ubuntu-latest
    needs: [configure]
    if: ${{ needs.configure.outputs.run_a == 'true' }}
    strategy:
      matrix:
        number: [1, 2]
    steps:
      - run: |
          echo ${{ matrix.number }}
          if [[ "${{ matrix.number }}" == "2" ]]; then
            echo "failing shard ${{ matrix.number}}"
            exit 1
          else
              echo "passing shard ${{ matrix.number }}"
          fi

  roll-up-a:
    needs: [a-shard]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - run: echo "a-shard failed" && exit 1
      # - run: echo a-shard-result=${{ needs.a-shard.result }}
      # - if: success()
      #   run: echo "success"
      # - if: cancelled()
      #   run: echo "cancelled"
      # - if: always()
      #   run: echo "always"
      # - if: ${{ needs.a-shard.result == 'failure' }}
      #   run: |
      #     echo "failing because b-shard failed"
      #     exit 1
      # - if: failure()
      #   run: |
      #     echo "failure"
      #     exit 1

  a-shard-did-fail:
    needs: [a-shard]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - run: exit 1

  b-shard:
    needs: [configure]
    if: ${{ needs.configure.outputs.run_b == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [1, 2]
    steps:
      - run: echo ${{ matrix.number }}

  roll-up-b:
    needs: [b-shard]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - run: echo "b-shard failed" && exit 1
      # - run: echo b-shard-result=${{ needs.b-shard.result }}
      # - if: success()
      #   run: echo "success"
      # - if: cancelled()
      #   run: echo "cancelled"
      # - if: always()
      #   run: echo "always"
      # - if: ${{ needs.b-shard.result == 'failure' }}
      #   run: |
      #     echo "failing because b-shard failed"
      #     exit 1
      # - if: failure()
      #   run: |
      #     echo "failure"
      #     exit 1

  b-shard-did-fail:
    needs: [b-shard]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - run: exit 1

  roll-up-all:
    runs-on: ubuntu-latest
    needs: [roll-up-a, roll-up-b, configure]
    if: ${{ !cancelled() && needs.configure.outputs.run_rollup_all == 'true' }}
    steps:
      - run: echo rollup-a-result=${{ needs.roll-up-a.result }}
      - run: echo rollup-b-result=${{ needs.roll-up-b.result }}
      - if: ${{ needs.roll-up-a.result == 'failure' }}
        run: echo "a failed" && exit 1
      - if: ${{ needs.roll-up-b.result == 'failure' }}
        run: echo "b failed" && exit 1
